trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

steps:
  # ✅ Checkout source code
  - task: Checkout@1
    displayName: 'Checkout source'

  # ✅ Install .NET SDK
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '7.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # ✅ Restore project dependencies
  - task: DotNetCoreCLI@2
    displayName: 'Restore project'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # ✅ Build the MVC project
  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # ✅ Publish the MVC app
  - task: DotNetCoreCLI@2
    displayName: 'Publish project'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  # ✅ Publish build artifacts to DevOps pipeline
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'mvc-app-drop'
      publishLocation: 'Container'
